### ISSUE TITLE
cant use unicode string

### ISSUE THREAD

**Issue by sgf** [gammasoft71/xtd.strings#1]
format(u"{}, {}!", u"Hello", u"你好"s);

**Comment by gammasoft71** [comment]
the the std::u16string and std::u32string was added to c++11, but method like std::stoi and others were not adapted to new string containers like u16string (c++11), u32string (c++11) and nor u8string (c++20).

In the same thinks, the input and output stream does not existe for u16string or u32string, only std::cin, std::cout, std::wcin and std::wcout exist. You must convert your string to std::string or std::string

The only correct string at this time is std::string and std::wstring.

**Remarks:**

the c++20 std::format(...) method is only too for std::string and std::wstring containers. see https://en.cppreference.com/w/cpp/utility/format/format

**workaround:**

use std::string to stock your utf8 strings like this:

#include <xtd/xtd.strings>
#include <iostream>

using namespace std;
using namespace std::literals;
using namespace xtd;

int main() {
  cout << format(u8"{}, {}!", u8"Hello", u8"你好"s) << endl;
}

// This code produces the following output:
//
// Hello, 你好!

**Comment by sgf** [comment]
thank you
